# Generated by Django 5.1.6 on 2025-03-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_internshipapplication_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('contacted', 'Contacted'), ('not_contacted', 'Not Contacted'), ('closed', 'Closed'), ('follow_up', 'Follow-Up'), ('alan_to_follow', 'Alan to Follow Up')], default='not_contacted', max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='category',
            field=models.CharField(blank=True, choices=[('pre_university', 'Pre-University Internships'), ('summer_internships', 'Summer Internships'), ('full_time', 'Full-Time Job Placements'), ('fundraising', 'Fundraising Dinner'), ('exploratory', 'Exploratory')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='lead_type',
            field=models.CharField(blank=True, choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot')], max_length=50, null=True),
        ),
    ]
