# Generated by Django 5.2.8 on 2025-11-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
